VoucherScrap/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.urls import path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('scrap.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrap/urls.py
from django.conf.urls import url
from .views import OfferView, Crawloffer

app_name = 'scrap'

urlpatterns = [
	url(r'^$', OfferView.as_view(), name='offerview'),
	url(r'^crawl_offers/$', Crawloffer.as_view(), name='crawl_offers'),
    ]

scrap/models.py
from django.db import models

# Create your models here.
class Offer(models.Model):
    coupon_id = models.CharField(max_length=100, unique=True)
    amount = models.CharField(max_length=100, null=True, blank=True)
    offer_value = models.CharField(max_length=50, null=True, blank=True)
    verified_on = models.CharField(max_length=100, null=True, blank=True)
    product = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    code = models.CharField(max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.amount) + " - " + str(self.offer_value)

scrap/views.py
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from django.http import HttpResponse, HttpResponseRedirect
from rest_framework.permissions import AllowAny
from .models import Offer
from .utils import crawl_offers
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
# Create your views here.

class OfferView(APIView):
    permission_classes = (AllowAny,)

    def get(self, request, format=None):
        page = request.GET.get('page_no')
        product_type_value = request.GET.get('product_category')
        coupon_type_value = request.GET.get('coupon_type')
        all_offers = Offer.objects.all().order_by('-id')
            
        product_set = set()
        coupon_type_set = set()
        for offer in all_offers:
            product_set.add(offer.product)
            coupon_type_set.add(offer.offer_value)

        if product_type_value and coupon_type_value:
            all_offers = all_offers.filter(product=product_type_value, offer_value=coupon_type_value).order_by('-id')
        elif product_type_value:
            all_offers = all_offers.filter(product=product_type_value).order_by('-id')
        elif coupon_type_value:
            all_offers = all_offers.filter(offer_value=coupon_type_value).order_by('-id')

        paginator = Paginator(all_offers, 25)
        if not page:
            page = 1
        try:
            all_offers = paginator.page(page)
        except:
            page = 1
            all_offers = paginator.page(page)
        return render(request, "scrap/offers.html", {"offers":all_offers, "product_set": product_set, "coupon_type_set": coupon_type_set, "product_type_value": product_type_value, "coupon_type_value": coupon_type_value})


class Crawloffer(APIView):
    permission_classes = (AllowAny,)

    def get(self, request, format=None):
        _ = crawl_offers()
        offer_objects = list()
        # _.append({"offer_id":"offer_id", "amount":"amount", "offer_value":"offer_value", "verified_on": "verified_on", "product":"product", "description":"description", "offer_code":"offer_code"})
        _.reverse()
        for offer in _:
            offer_objects.append(Offer(coupon_id=offer['offer_id'], amount=offer['amount'], offer_value=offer['offer_value'], verified_on=offer['verified_on'], product=offer['product'], description=offer['description'], code=offer['offer_code']))
        # try:
        Offer.objects.bulk_create(offer_objects, ignore_conflicts=True)
        return redirect("scrap:offerview")

scrap/templates/scrap/offers.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>
      Travel Offers
    </title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <script
      type="text/javascript"
      src="{% static 'assets/js/function.js' %}"
    ></script>
  </head>
  <body class="body">
    <div class="heading">All Offers</div>
    <div class="header">
      <div class="product-filter">
        <label class="label-class">Filter :</label>
        <select id="product_type" onchange="filter('{{ offers.number }}')">
          <option value="" selected> -- </option>
          {% for product in product_set %} 
          {% if product == product_type_value %}
          <option value="{{ product }}" selected>{{ product }}</option>
          {% else %}
          <option value="{{ product }}">{{ product }}</option>
          {% endif %} {% endfor %}
        </select>
      </div>
      <div class="product-filter">
        <label class="label-class">Type :</label>
        <select id="coupon_type" onchange="filter('{{ offers.number }}')">
          <option value="" selected> -- </option>
          {% for coupon_type in coupon_type_set %} {% if coupon_type == coupon_type_value %}
          <option value="{{ coupon_type }}" selected>{{ coupon_type }}</option>
          {% else %}
          <option value="{{ coupon_type }}">{{ coupon_type }}</option>
          {% endif %} {% endfor %}
        </select>
      </div>
      <div class="page-no">
        <a href="{% url 'scrap:crawl_offers' %}"><button class="refresh-button">Refresh Offers</button></a>
      </div>
      <div class="page-no">
        <label class="label-class">Pages :</label>
        {{ offers.number }}/{{ offers.paginator.num_pages }}
      </div>
    </div>
    {% if offers %} {% for offer in offers %}
    <div class="coupon-box">
      <div class="coupon-value">
        <span class="coupon-text">{{ offer.amount }}</span>
        <span class="coupon-rest-text">{{ offer.offer_value }}</span>
        <div class="coupon-type">
          <span>{{ offer.product }}</span>
        </div>
      </div>
      <div class="coupon-description-box">
        <p class="coupon-verification">{{ offer.verified_on }}</p>
        <p class="coupon-description">
          {{ offer.description }}
        </p>
      </div>
      {% if offer.code %}
      <div class="coupon-code">
        {{ offer.code }}
      </div>
      {% endif %}
    </div>
    {% endfor %} {% else %}
    <h3 style="text-align:center;">No Offers Available</h3>
    {% endif %}

    <div class="footer">
      {% if offers.has_previous %}
      <button
        class="button"
        onclick="filter('{{ offers.previous_page_number }}')"
      >
        Prev
      </button>
      {% else %}
      <button class="button" disabled>Prev</button>
      {% endif %} {% if offers.has_next %}
      <button
        class="button"
        onclick="filter('{{ offers.next_page_number }}')"
      >
        Next
      </button>
      {% else %}
      <button class="button" disabled>Next</button>
      {% endif %}
    </div>
  </body>
</html>